### ISSUE TITLE
Unable to Customize SCALE of Charging Flash

### ISSUE THREAD

**Issue by hiiiP0wer** [Umerbhat/react-battery-gauge#14]
### Bug Description:
In the current version of the react battery SVG gauge package, I cannot customize the scale of the flash animation despite having the option to pass a `chargingFlash` object with a scale parameter in the customization prop.

### Steps to Reproduce:
1. Initialize the gauge component with `customization` prop options including a chargingFlash object with a non-undefined scale value and `charging` set to true.
2. Observe that the scale of the Charging flash remains unaffected by the provided value.

**Comment by Umerbhat** [comment]
Yes, I could see the scale is misplaced. Thanks for your contribution 🥇
