### ISSUE TITLE
value wont change 

### ISSUE THREAD

**Issue by ShoLn** [Umerbhat/react-battery-gauge#4]
I want to change the value while pass different number to the value prop, 
but  the value of battery wont change if the animated prop is added

**Comment by Umerbhat** [comment]
> I want to change the value while pass different number to the value prop, but the value of battery wont change if the animated prop is added

Thanks for raising it. Will look into this at priority

**Comment by Umerbhat** [comment]
Fixed [here](https://github.com/Umerbhat/react-battery-gauge/pull/5), fix will be available on version `1.0.4`

**Comment by ShoLn** [comment]
Thx for fixing it !
