### ISSUE TITLE
Warning: Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by vasylHordynskyy** [Umerbhat/react-battery-gauge#6]
Hi,
First of all thanks for the great component.

I have noticed when we are using react-battery-gauge and pass gradFill for gradient then we got warning in console. (Warning: Each child in a list should have a unique "key" prop.)

Unfortunately there are no way to pass key for gradient to get rid of this warning.
Here is link to example where this warning is shown: [example](https://codesandbox.io/s/floral-voice-i2jsb5?file=/src/App.tsx)

Thanks in advance.

**Comment by Umerbhat** [comment]
Hello!

Thank you for bringing this issue to our attention. We appreciate your feedback and are glad to hear that you find react-battery-gauge helpful.

Regarding the warning you mentioned, we apologize for any inconvenience it may have caused. We will fix it as soon as possible.

Thank you again for your contribution to our project.

**Comment by Umerbhat** [comment]
Fixed in `v1.0.5`
