### ISSUE TITLE
Is it possible to render text instead of a % value?

### ISSUE THREAD

**Issue by andronikosnedos-temboo** [Umerbhat/react-battery-gauge#7]
Thanks for the library, works great!

We have a use case in an IoT application where the battery level might be unknown and we'd like to render an `!` or some other combination to designate the particular state. Is there any way to make it happen with this library?

**Comment by Umerbhat** [comment]
Thank you for your kind words about the library!

Regarding your use case, the library does not currently have a built-in feature for displaying any other text. However, I find it to be a good use case.

Thanks for your contribution

**Comment by Umerbhat** [comment]
`formatValue` prop in #8 (available in v1.0.5)

**Comment by andronikosnedos-temboo** [comment]
Great stuff, so if I understand from the PR, `formatValue` is a function that accepts the numerical value but can return a string instead of the number, right?

**Comment by Umerbhat** [comment]
> Great stuff, so if I understand from the PR, `formatValue` is a function that accepts the numerical value but can return a string instead of the number, right?

Yes, you can return a number or string

**Comment by andronikosnedos-temboo** [comment]
Works well, thanks a lot for implementing it so fast!
